### ISSUE TITLE
Using JSON-LD string in toRDF

### ISSUE THREAD

**Issue by fils** [kazarena/json-gold#13]
So I see the examples where you can do

```
    triples, err := proc.ToRDF("URL here", options)
```

or 

```
triples, err := proc.ToRDF(map[string]interface{}, options)
```

What is I have a JSON-LD string?  What is the process of getting the string into an interface{} format that can be used here?

```
triples, err := proc.ToRDF("Valid JSON-LD string", options)
```

It seems when I pass it a URL it's simply reading in the JSON-LD at some point, so I do not see how to get to the point where I am just passing it a JSON-LD string to work with.  

Thanks!

**Comment by kazarena** [comment]
@fils,

This should work:

```
import (
    "encoding/json"
)
...
myString := `{
    "key": "value"
}`
var myInterface interface{}

err := json.Unmarshal([]byte(myString), &myInterface)
if err != nil {
...
}

triples, err := proc.ToRDF(myInterface, options)
```

_Note: I didn't compile/run this code so it may contain typos._

Regards,
Stan

**Comment by fils** [comment]
@kazarena 

Stan,
  Thanks....  I tried tis but when I run it I get:

```
Fils:jsongold dfils$ go run main.go
&{map[@default:[0xc420070ec0 0xc420070f00 0xc420070f40 0xc420070f80 0xc420070fc0 0xc420071040 0xc420071080 0xc420071100 0xc420071140 0xc420071180 0xc4200711c0 0xc420071200 0xc420071240 0xc420071280 0xc4200712c0 0xc420071300 0xc420071340 0xc420071380 0xc4200713c0 0xc420071400 0xc420071440 0xc420071480 0xc4200714c0 0xc420071500 0xc420071540 0xc420071580 0xc4200715c0 0xc420071600]] map[]}
Fils:jsongold dfils$
```

My code is at:  https://github.com/OpenCoreData/ocdGarden/blob/master/jsongold/main.go

The restTest() function in there works great.  I can pull my JSON-LD down from a REST call, convert it to RDF and then convert it back into JSON-LD.   the stringTest() isn't really doing that though and I am still not sure why.  I tried to make it fit the example above.  

Also..  thank you much for this package.  I am learning how poor my JSON-LD was and it's really improving as I use this code to make sure I can move the material around.  Really appreciate you making this and putting it out there!

**Comment by kazarena** [comment]
@fils : almost everything is good now. You forgot one small thing:

```
options.Format = "application/nquads"
```

(see examples)

Without specifying the desired format (only _application/nquads_ is currently supported) you receive *ld.RDFDataset back.

I should probably make it a default to avoid this confusion.

**Comment by fils** [comment]
@kazarena 

Thanks!  I smacked my palm to my my forehead when I read your post..  I felt like I should have caught that one since I had set it in the function below it.  But I didn't !  

It's working ....  really appreciate your time and help!

**Comment by kazarena** [comment]
@fils: you are welcome!
