### ISSUE TITLE
Releases + Tags

### ISSUE THREAD

**Issue by doertedev** [kazarena/json-gold#17]
Hey there.

Is it possible to do releases or tags here?

Love, someone having to maintain a Gopkg.toml

**Comment by kazarena** [comment]
Hi @doertedev,

Certainly. I will address it shortly.

Regards,
Stan

**Comment by kazarena** [comment]
@doertedev, see https://github.com/kazarena/json-gold/releases/tag/v0.1.0.

I'll be tagging releases going forward.

Stan

**Comment by doertedev** [comment]
Very much appreciated! Thanks for the rapid tag.
