### ISSUE TITLE
Change of maintainer (Dec 2017)

### ISSUE THREAD

**Issue by kazarena** [kazarena/json-gold#20]
Dear users of JSON-goLD,

We are planning to add new features to this library, including support for Linked Data Signatures, content-addressable JSON-LD, etc. In order to facilitate this development, the current maintainer of JSON-goLD (@kazarena) is going to copy this repository to the GitHub organisation of his company (@piprate) under the following terms:

* @piprate team will be the maintainer of the new library (__github.com/piprate/json-gold__)
* This repo (__github.com/kazarena/json-gold__) will remain available
* Interfaces of the new library will be preserved, but may deviate in future versions
* Licensing will not change
* Past contributors will be recognised
* Commit history will *not* be preserved in the new library
* Versions of the new library will be reset

I've decided the standard GitHub repo transfer process will not work well because of Go imports. Fork isn't ideal either because the original library will receive no further updates.

Please leave your feedback here.

**Comment by fils** [comment]
As a user of this package..   simply ..  THANKS...  
it's been so wonderful having a solid JSON-LD library in Go!

**Comment by mbana** [comment]
It would be nice if you provided a link to the new repo in the `README.md`.

**Comment by kazarena** [comment]
@mbana Done
