### ISSUE TITLE
Frame adds an extra empty string element to some singleton sets

### ISSUE THREAD

**Issue by hapnermw** [kazarena/json-gold#9]
Here's a program that reproduces this issue.
[tst.txt](https://github.com/kazarena/json-gold/files/50294/tst.txt)

**Comment by kazarena** [comment]
Thanks, I'll take a look

**Comment by kazarena** [comment]
I'm re-posting the original issue from #4 here to provide some context:

---

Hi Again,

I've come across another bug in frame. It is converting

[
                  {
                    "@type": "
http://privacy.pn.schema.webshield.io/octx#aetna_poc_1",
                    "@value":
"MIICAwYJKoZIhvcNAQcDoIIB9DCCAfACAQAxggGrMIIBpwIBADCBjjB3MQswCQYD\nVQQGEwJVUzETMBEGA1UEChMKQWV0bmEgSW5jLjEoMCYGA1UECxMfR2VvUm9vdCBD\nZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEpMCcGA1UEAxMgQWV0bmEgSW5jLiBDZXJ0\naWZpY2F0ZSBBdXRob3JpdHkCEz4AACq958ozFBQZpjsAAAAAKr0wDQYJKoZIhvcN\nAQEBBQAEggEADhOnJeJQEjL5zzhV6gptV14jGRWzgSQdTn+rWhKkJLhexNpZv9oh\nVfQeNnAhw+xPNtyDwWYi1Exy+OmDiGU1hqFAZ+GFWXEANF8ZSTrvkFlWwinJr8U0\nUG65VU8ogMiVT/xv9Un03SL7OrqvthwU36orTl1p5pyT4o+zwhA7V+R5iOic7WfT\nIwyVGns7PlD/iSinCJJJh+sr1mXvcisMRPjcPpBREti6W28YxvMwYOWee2c2/L+9\nhR/pSy2KwnPUBE8+dgRnspvyrOJH3XLIT9KQDjEfNZi4WBuznWCRrxSTuc378kva\nzv6qcZtu9iXI+4rqIOvb31g2lzpPXLnedTA8BgkqhkiG9w0BBwEwHQYJYIZIAWUD\nBAEqBBDQ67YPeZZZTfKInoMl0P1KgBBjxTuxyYt5XcGfGg8c2UXl\n"
                  }
 ]

to

[
                {
                  "@type": "
http://privacy.pn.schema.webshield.io/octx#aetna_poc_1",
                  "@value":
"MIICAwYJKoZIhvcNAQcDoIIB9DCCAfACAQAxggGrMIIBpwIBADCBjjB3MQswCQYD\nVQQGEwJVUzETMBEGA1UEChMKQWV0bmEgSW5jLjEoMCYGA1UECxMfR2VvUm9vdCBD\nZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEpMCcGA1UEAxMgQWV0bmEgSW5jLiBDZXJ0\naWZpY2F0ZSBBdXRob3JpdHkCEz4AACq958ozFBQZpjsAAAAAKr0wDQYJKoZIhvcN\nAQEBBQAEggEADhOnJeJQEjL5zzhV6gptV14jGRWzgSQdTn+rWhKkJLhexNpZv9oh\nVfQeNnAhw+xPNtyDwWYi1Exy+OmDiGU1hqFAZ+GFWXEANF8ZSTrvkFlWwinJr8U0\nUG65VU8ogMiVT/xv9Un03SL7OrqvthwU36orTl1p5pyT4o+zwhA7V+R5iOic7WfT\nIwyVGns7PlD/iSinCJJJh+sr1mXvcisMRPjcPpBREti6W28YxvMwYOWee2c2/L+9\nhR/pSy2KwnPUBE8+dgRnspvyrOJH3XLIT9KQDjEfNZi4WBuznWCRrxSTuc378kva\nzv6qcZtu9iXI+4rqIOvb31g2lzpPXLnedTA8BgkqhkiG9w0BBwEwHQYJYIZIAWUD\nBAEqBBDQ67YPeZZZTfKInoMl0P1KgBBjxTuxyYt5XcGfGg8c2UXl\n"
                },
                ""
]

So, in some cases it is adding an empty string as a second element of a
singleton value object array.

**Comment by kazarena** [comment]
@hapnermw,

Right, so the issue lies in your JSON. You have 2 objects with the same id: _http://id.webshield.io/com/aetna#012-345-JH_. While the first object contains the following definition of _http://aetna.schema.webshield.io/prop#SSN_ field:

```
"http://aetna.schema.webshield.io/prop#SSN": {
    "@type": "http://privacy.pn.schema.webshield.io/octx#aetna_poc_1",
    "@value": "MIICAwYJKoZIhvcNAQcDoIIB9DCCAfACAQAxggGrMIIBpwIBADCBjjB3MQswCQYD\nVQQGEwJVUzETMBEGA1UEChMKQWV0bmEgSW5jLjEoMCYGA1UECxMfR2VvUm9vdCBD\nZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEpMCcGA1UEAxMgQWV0bmEgSW5jLiBDZXJ0\naWZpY2F0ZSBBdXRob3JpdHkCEz4AACq958ozFBQZpjsAAAAAKr0wDQYJKoZIhvcN\nAQEBBQAEggEADhOnJeJQEjL5zzhV6gptV14jGRWzgSQdTn+rWhKkJLhexNpZv9oh\nVfQeNnAhw+xPNtyDwWYi1Exy+OmDiGU1hqFAZ+GFWXEANF8ZSTrvkFlWwinJr8U0\nUG65VU8ogMiVT/xv9Un03SL7OrqvthwU36orTl1p5pyT4o+zwhA7V+R5iOic7WfT\nIwyVGns7PlD/iSinCJJJh+sr1mXvcisMRPjcPpBREti6W28YxvMwYOWee2c2/L+9\nhR/pSy2KwnPUBE8+dgRnspvyrOJH3XLIT9KQDjEfNZi4WBuznWCRrxSTuc378kva\nzv6qcZtu9iXI+4rqIOvb31g2lzpPXLnedTA8BgkqhkiG9w0BBwEwHQYJYIZIAWUD\nBAEqBBDQ67YPeZZZTfKInoMl0P1KgBBjxTuxyYt5XcGfGg8c2UXl\n"
},
```

the second object has:

```
"http://aetna.schema.webshield.io/prop#SSN": "",
```

Framing algorithm will think it's the same object and merge the properties together, as you reported:

```
[
  {
    "@type": "http://privacy.pn.schema.webshield.io/octx#aetna_poc_1",
    "@value": "MIICAwYJKoZIhvcNAQcDoIIB9DCCAfACAQAxggGrMIIBpwIBADCBjjB3MQswCQYD\nVQQGEwJVUzETMBEGA1UEChMKQWV0bmEgSW5jLjEoMCYGA1UECxMfR2VvUm9vdCBD\nZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEpMCcGA1UEAxMgQWV0bmEgSW5jLiBDZXJ0\naWZpY2F0ZSBBdXRob3JpdHkCEz4AACq958ozFBQZpjsAAAAAKr0wDQYJKoZIhvcN\nAQEBBQAEggEADhOnJeJQEjL5zzhV6gptV14jGRWzgSQdTn+rWhKkJLhexNpZv9oh\nVfQeNnAhw+xPNtyDwWYi1Exy+OmDiGU1hqFAZ+GFWXEANF8ZSTrvkFlWwinJr8U0\nUG65VU8ogMiVT/xv9Un03SL7OrqvthwU36orTl1p5pyT4o+zwhA7V+R5iOic7WfT\nIwyVGns7PlD/iSinCJJJh+sr1mXvcisMRPjcPpBREti6W28YxvMwYOWee2c2/L+9\nhR/pSy2KwnPUBE8+dgRnspvyrOJH3XLIT9KQDjEfNZi4WBuznWCRrxSTuc378kva\nzv6qcZtu9iXI+4rqIOvb31g2lzpPXLnedTA8BgkqhkiG9w0BBwEwHQYJYIZIAWUD\nBAEqBBDQ67YPeZZZTfKInoMl0P1KgBBjxTuxyYt5XcGfGg8c2UXl\n"
  },
  ""
]
```

It kind of makes sense.

**Comment by hapnermw** [comment]
Thanks, I should have seen that. I'm not the one who creates this JSON LD
so I should have looked closer for stupid mistakes ...

I've this this general issue before with dup @id's 'corrupting' the data.
Sorry to have wasted your time with this.

**Comment by kazarena** [comment]
No problem at all!

**Comment by hapnermw** [comment]
The problem with frame is that its does what you tell it :>)
